const FORMAT_BR = "DD/MM/YYYY";
const FORMAT_BR_HOUR = "DD/MM/YYYY HH:mm";
const FORMAT_GLOBAL_DATE = "YYYY-MM-DD";
const FORMAT_GLOBAL_DATEHOUR = "YYYY-MM-DD HH:mm";

export {
  FORMAT_BR,
  FORMAT_BR_HOUR,
  FORMAT_GLOBAL_DATE,
  FORMAT_GLOBAL_DATEHOUR,
};
