export const paths = {
  APARTAMENTOS: "APARTAMENTOS",
  APARTAMENTOS_LISTAR: "APARTAMENTOSLISTAR",
  CADASTRO: "CADASTRO",
  CLIENTE: "CLIENTE",
  HISTORICO: "HISTORICO",
  LOGIN: "LOGIN",
  QUARTO_LISTAR: "QUARTOLISTAR",
  QUARTO: "QUARTO",
};
